on: 
  push:
  workflow_dispatch:
    
env:
  greeting: "Hello"
  name: "Dan"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # - run: |
      #     export PUBLIC_IP_ADDRESS=$(curl --silent https://api.ipify.org)
      #     echo "PUBLIC_IP_ADDRESS=${PUBLIC_IP_ADDRESS}" >> $GITHUB_ENV
      #     echo "PUBLIC_IP=${PUBLIC_IP_ADDRESS}" 
      #     echo $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: petroill/test
          ref: branch
          path: test      
      - id: foo
        uses: petroill/test/.github/actions/test@branch
        with:
          who-to-greet: 'Testing'
          # who-to-greet: ${name}
          public-ip-address: ''
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash