on: 
  workflow_dispatch:

env:
  greeting: "Hello"
  name: "Dan"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-python@v3
        with:
         python-version: '3.10.4' 
      - run: pwd
      - run: ls
      - run: python3 .github/myscrypt.py

      - run: bash helloworld.sh